experiment_name: baseline_25d_5slide_binary
dataset_name: Dataset002_BHSD_Binary
dataset_id: 2
configuration: 2d
trainer: nnUNetTrainer_25D_5Slice
folds: [0]
device: cuda
save_npz: true
validation_checkpoint: best
inference_checkpoint: checkpoint_best.pth
resume: false
disable_checkpointing: false
seed: 3407
nnunet_n_proc_da: 4
max_num_epochs: 1000
early_stop_min_epochs: 300
early_stop_patience: 100
early_stop_min_delta: 0.0001
early_stop_metric: ema_fg_dice
plans: nnUNetPlans
slice_mode: naive
num_input_slices: 5
ground_truth_dir: null
inference_input: null
