experiment_name: baseline_25d_3slide
dataset_name: Dataset001_BHSD
dataset_id: 1
configuration: 2d
trainer: nnUNetTrainer_25D
folds: [0]
device: cuda
save_npz: false
resume: false
disable_checkpointing: false
seed: 3407
nnunet_n_proc_da: 4
max_num_epochs: 1000
early_stop_patience: 50
early_stop_min_delta: 0.0001
early_stop_metric: ema_fg_dice
plans: nnUNetPlans
slice_mode: naive
num_input_slices: 3
ground_truth_dir: null
inference_input: null
