experiment_name: feature_fusion_25d_bottleneck_3slice
dataset_name: Dataset001_BHSD
dataset_id: 1
configuration: 2d
trainer: nnUNetTrainer25DFeatureFusionBottleneck
folds: [0]
device: cuda
save_npz: false
resume: false
disable_checkpointing: false
seed: 3407
nnunet_n_proc_da: 4
plans: nnUNetPlans
slice_mode: feature_fusion_bottleneck
num_input_slices: 3
ground_truth_dir: null
inference_input: null
