experiment_name: spacing_aware_25d
dataset_name: Dataset001_BHSD
dataset_id: 1
configuration: 2d
trainer: nnUNetTrainer_SpacingAware25D
folds: [0]
device: cuda
save_npz: true
resume: false
disable_checkpointing: false
seed: 3407
nnunet_n_proc_da: 4
plans: nnUNetPlans
slice_mode: spacing_aware
num_input_slices: 3
spacing_csv: bhsd_spacing_summary.csv
ground_truth_dir: null
inference_input: null
